spring.application.name=VSR_Backend_AI
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2,TLSv1.3
spring.datasource.username=3ZjQyfKJxcXrH9x.root
spring.datasource.password=veZ37f7mXTx46thG
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Cloudinary config
cloudinary.cloud-name=djdjlx9j8
cloudinary.api-key=442491438142273
cloudinary.api-secret=Bo7sTwVCiuPOfqAcTD7pJwrwGd8